version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: build
          command: echo "Building..."
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: test
          command: echo "Testing..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
