version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: build
          command: echo "Building..."
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: test
          command: echo "Testing..."
  deploy-master:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy dev release.
          command: echo "Deploying dev release on master branch..."
  deploy-alpha:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy edge release.
          command: echo "Deploying edge release based on Git tag..."
  deploy-stable:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy stable release.
          command: echo "Deploying stable release based on Git tag..."
  docs-build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Build docs for release.
          command: echo "Building docs for release..."

workflows:
  version: 2
  workflow1:
    filters:
      tags:
        only: /.*/
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
  workflow2:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
