version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: build
          command: echo "Building..."
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: test
          command: echo "Testing..."
  deploy-master:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy dev release.
          command: echo "Deploying dev release on master branch..."
  deploy-alpha:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy edge release.
          command: echo "Deploying edge release based on Git tag..."
  deploy-release:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy stable release.
          command: echo "Deploying stable release based on Git tag..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy-master:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-alpha:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*-alpha/
      - deploy-release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[^-+]*$/
